# Generated by Django 5.0 on 2024-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0002_beercheckin_in_bar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beercheckin",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
