# Generated by Django 5.0 on 2023-12-28 14:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0002_beer_created_at_beercheckin_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beertype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="beertype",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="type_unique_lower_case_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="brand_unique_lower_case_name",
            ),
        ),
    ]
