# Generated by Django 5.0 on 2024-02-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0003_alter_beercheckin_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="beercheckin",
            name="joint_checkin",
            field=models.ManyToManyField(
                blank=True, related_name="joint_checkin", to="beers.user"
            ),
        ),
    ]
